_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.1
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
Loss:
    value: BCE
batch_size:
    value: 256
epochs:
    value: 20
optimizer:
    value: Adam
